# MySQL source address, user and password
# user must have replication privilege in MySQL.
source_addr = "ip:3306"
source_user = "user"
source_pass = "pass"
source_charset = "utf8"

# MySQL sink address, user and password
sink_addr = "127.0.0.1:3306"
sink_user = "root"
sink_pass = "pass"
sink_charset = "utf8"

# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing. 
# TODO: support other storage, like etcd. 
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

# Ignore table without primary key
skip_no_pk_table = false

# MySQL data source
[[source]]
schema = "db_evorder"

tables = ["t_delivery_detail", "romp_sign"]

[[rule]]
source_schema = "db_evorder"
source_table = "t_delivery_detail"
sink_schema = "mysqlsync_sink"
sink_table = "t_delivery_detail"

[[rule]]
source_schema = "db_evorder"
source_table = "romp_sign"
sink_schema = "mysqlsync_sink"
sink_table = "romp_sign"