# MySQL source address, user and password
# user must have replication privilege in MySQL.
source_addr = "127.0.0.1:3306"
source_user = "root"
source_pass = ""
source_charset = "utf8"

# MySQL mysql address, user and password
sink_addr = "127.0.0.1:3306"
sink_user = "root"
sink_pass = ""
sink_charset = "utf8"

# Set true when elasticsearch use https
#es_https = false
# Elasticsearch address
es_addr = "127.0.0.1:9200"
# Elasticsearch user and password, maybe set by shield, nginx, or x-pack
es_user = ""
es_pass = ""

# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing. 
# TODO: support other storage, like etcd. 
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 1

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

# Ignore table without primary key
skip_no_pk_table = false

# MySQL data source
[[source]]
schema = "mysqlsync"

tables = ["user"]

[[rule]]
schema = "mysqlsync"
table = "user"
source_schema = "mysqlsync"
source_table = "user"
sink_schema = "mysqlsync_sink"
sink_table = "user_sink"